services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - DATABASE_URL=postgres://pguser:pgpassword@localhost:5433/pgdb
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
