services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - DATABASE_URL=postgres://pguser:pgpassword@localhost:5433/pgdb
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis-db:
    image: redis:latest
    # environment:
      # - REDIS_LOCAL_URL : redis://localhost:6380/
      # - REDIS_DOCKER_URL : redis://redis-db:6380/
    ports:
      - 6380:6379
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
