# Generated by Django 5.2.6 on 2025-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
